theme: jekyll-theme-dinky
github:
  is_project_page: false
title: [Welcome to AATHITH's Tech Blog]
description: [I wrote this blog for my self-reference. It may be helpful for you to get an idea on the below topics]
