kind: Service
apiVersion: v1
metadata:
  name: appserver-pipeline
spec:
  type: NodePort
  selector:
    app: appserver-pipeline
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30102
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
