theme: jekyll-theme-cayman
github:
  is_project_page: false
title: [Intro to Prometheus]
description: [This page will give you an intro on what Prometheus is, How to deploy it in K8's cluster and Visualising the data using Grafana]
