apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-server
  name: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  type: NodePort
status:
  loadBalancer: {}
